<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Faq;

class FaqSeeder extends Seeder
{
    public function run(): void
    {
        $faqs = [
            [
                'question'                => 'What is EduFlow, and who is it designed for?',
                'slug'                    => 'what-is-eduflow-and-who-is-it-designed-for',
                'answer'                  => 'EduFlow is a comprehensive school management platform designed to streamline academic administration, student admissions, fee collections, human resources, transport, library, and inventory workflows for modern educational institutions. It serves school administrators, teachers, accountants, parents, students, and staff by unifying daily campus operations into a secure, role-based workspace.',
                'category'                => 'General / Account',
                'status'                  => 'published',
                'is_featured_on_homepage' => true,
                'sort_order'              => 1,
                'published_at'            => now(),
            ],
            [
                'question'                => 'What major school management functions does EduFlow provide?',
                'slug'                    => 'what-major-school-management-functions-does-eduflow-provide',
                'answer'                  => "EduFlow brings multiple school operations into one platform, including:\n\n2.1 Student Management\nStudent registration, profiles, admissions, documents, promotion, and related student lifecycle workflows.\n\n2.2 Academic Management\nExaminations, marks, CBC assessments, homework, grading scales, and academic reporting.\n\n2.3 Finance & Fees\nFee structures, payments, invoices, balances, payment methods, and financial reporting.\n\n2.4 Campus Operations\nTransport, hostels, inventory, library circulation, visitor management, and co-curricular activities.",
                'category'                => 'School Management',
                'status'                  => 'published',
                'is_featured_on_homepage' => true,
                'sort_order'              => 2,
                'published_at'            => now(),
            ],
            [
                'question'                => 'How does EduFlow help schools manage students and admissions?',
                'slug'                    => 'how-does-eduflow-help-schools-manage-students-and-admissions',
                'answer'                  => 'The admissions and student management module allows administrative staff to register students, generate unique admission numbers, manage student profile records, upload required student documents, assign students to classes and streams, and process student promotions across academic years. It also includes bulk CSV import and export templates to simplify onboarding large cohorts.',
                'category'                => 'Students & Admissions',
                'status'                  => 'published',
                'is_featured_on_homepage' => false,
                'sort_order'              => 3,
                'published_at'            => now(),
            ],
            [
                'question'                => 'How does EduFlow support teachers, staff, HR, and payroll?',
                'slug'                    => 'how-does-eduflow-support-teachers-staff-hr-and-payroll',
                'answer'                  => 'EduFlow provides comprehensive human resources tools for managing staff profiles, departments, designations, joining dates, and employment status. Staff members can manage leave requests, view payslips, and track payroll computations while administrators configure secure staff permissions and document storage.',
                'category'                => 'Staff / HR',
                'status'                  => 'published',
                'is_featured_on_homepage' => false,
                'sort_order'              => 4,
                'published_at'            => now(),
            ],
            [
                'question'                => 'How does EduFlow handle academics, examinations, CBC assessment, homework, and grading?',
                'slug'                    => 'how-does-eduflow-handle-academics-examinations-cbc-assessment-homework-and-grading',
                'answer'                  => 'The academics module enables teachers to assign homework, record examination marks, configure grade scales, and input formative and summative Competency-Based Curriculum (CBC) assessment scores mapped against approved learning strands and performance descriptors. Report cards and academic summaries can then be generated systematically.',
                'category'                => 'Academics',
                'status'                  => 'published',
                'is_featured_on_homepage' => true,
                'sort_order'              => 5,
                'published_at'            => now(),
            ],
            [
                'question'                => 'How does EduFlow manage school fees, payments, billing, and financial records?',
                'slug'                    => 'how-does-eduflow-manage-school-fees-payments-billing-and-financial-records',
                'answer'                  => 'School accountants can set up structured fee categories, assign fee structures by class or term, record cash, bank, or online payments (such as Paystack integration), generate official payment receipts, and track student fee balances in real time. Unallocated payments are stored securely for subsequent termly reconciliation.',
                'category'                => 'Fees & Finance',
                'status'                  => 'published',
                'is_featured_on_homepage' => true,
                'sort_order'              => 6,
                'published_at'            => now(),
            ],
            [
                'question'                => 'Can EduFlow help schools manage fee defaulters, financial reports, and payment reconciliation?',
                'slug'                    => 'can-eduflow-help-schools-manage-fee-defaulters-financial-reports-and-payment-reconciliation',
                'answer'                  => 'Yes. EduFlow generates detailed financial summaries, income statements, fee collection reports, and automated or manual defaulter lists. Accountants can audit transaction logs, verify payment gateway references, and review unallocated wallets to maintain accurate accounting records.',
                'category'                => 'Fees & Finance',
                'status'                  => 'published',
                'is_featured_on_homepage' => false,
                'sort_order'              => 7,
                'published_at'            => now(),
            ],
            [
                'question'                => 'How does EduFlow manage parents, students, guardians, and communication?',
                'slug'                    => 'how-does-eduflow-manage-parents-students-guardians-and-communication',
                'answer'                  => 'EduFlow links students directly to their respective parents and guardians. Authorized users can access contact directories, track student attendance, view performance reports, and leverage integrated notification channels for announcements and fee reminders.',
                'category'                => 'General / Account',
                'status'                  => 'published',
                'is_featured_on_homepage' => false,
                'sort_order'              => 8,
                'published_at'            => now(),
            ],
            [
                'question'                => 'How does EduFlow support school transport management?',
                'slug'                    => 'how-does-eduflow-support-school-transport-management',
                'answer'                  => 'The transport module allows administrators to register vehicles, define transport routes, assign drivers, manage pickup and dropoff points, and link students to specific transport schedules and associated transport fees.',
                'category'                => 'Transport',
                'status'                  => 'published',
                'is_featured_on_homepage' => false,
                'sort_order'              => 9,
                'published_at'            => now(),
            ],
            [
                'question'                => 'How does EduFlow support hostels, boarding, rooms, and student accommodation?',
                'slug'                    => 'how-does-eduflow-support-hostels-boarding-rooms-and-student-accommodation',
                'answer'                  => 'Boarding facilities can be managed by defining hostel buildings, rooms, bed capacities, and warden assignments. Administrators can allocate students to rooms and monitor boarding occupancy in real time.',
                'category'                => 'Hostel',
                'status'                  => 'published',
                'is_featured_on_homepage' => false,
                'sort_order'              => 10,
                'published_at'            => now(),
            ],
            [
                'question'                => 'How does EduFlow manage inventory, assets, stores, and stock control?',
                'slug'                    => 'how-does-eduflow-manage-inventory-assets-stores-and-stock-control',
                'answer'                  => 'EduFlow provides inventory tracking across school stores. Staff can record item categories, supplier purchases, stock issues, asset assignments, and periodic inventory audits to maintain accountability for physical school property.',
                'category'                => 'Inventory & Assets',
                'status'                  => 'published',
                'is_featured_on_homepage' => false,
                'sort_order'              => 11,
                'published_at'            => now(),
            ],
            [
                'question'                => 'How does EduFlow support libraries, books, circulation, and library records?',
                'slug'                    => 'how-does-eduflow-support-libraries-books-circulation-and-library-records',
                'answer'                  => 'Librarians can maintain a digital book catalogue, manage ISBNs and copy numbers, track book circulation (issues and returns), calculate overdue fines, and monitor borrowing history for students and staff members.',
                'category'                => 'Library',
                'status'                  => 'published',
                'is_featured_on_homepage' => false,
                'sort_order'              => 12,
                'published_at'            => now(),
            ],
            [
                'question'                => 'How does EduFlow manage visitors, gate operations, and school security records?',
                'slug'                    => 'how-does-eduflow-manage-visitors-gate-operations-and-school-security-records',
                'answer'                  => 'The visitor management module logs visitor entries and exits at school gates. Security personnel record visitor names, phone numbers, ID numbers, vehicle registrations, whom they are meeting, and the purpose of visit to generate secure gate logs.',
                'category'                => 'Visitor Management',
                'status'                  => 'published',
                'is_featured_on_homepage' => false,
                'sort_order'              => 13,
                'published_at'            => now(),
            ],
            [
                'question'                => 'How does EduFlow support sports, co-curricular activities, talents, houses, and student achievements?',
                'slug'                    => 'how-does-eduflow-support-sports-co-curricular-activities-talents-houses-and-student-achievements',
                'answer'                  => 'Schools can organize co-curricular programs, sports teams, competitive houses, and house point awards. The system tracks student participation, achievements, and talent passport records to encourage holistic student development.',
                'category'                => 'Co-Curricular / Talent',
                'status'                  => 'published',
                'is_featured_on_homepage' => false,
                'sort_order'              => 14,
                'published_at'            => now(),
            ],
            [
                'question'                => 'Does EduFlow support reports, CSV imports/exports, PDFs, printing, and bulk data operations?',
                'slug'                    => 'does-eduflow-support-reports-csv-imports-exports-pdfs-printing-and-bulk-data-operations',
                'answer'                  => 'Yes. EduFlow provides export tools for generating CSV streams, tabular reports, and printable PDF documents for student lists, fee statements, report cards, and financial audits. Standardized CSV import templates are also available for bulk data entry.',
                'category'                => 'Import / Export',
                'status'                  => 'published',
                'is_featured_on_homepage' => false,
                'sort_order'              => 15,
                'published_at'            => now(),
            ],
            [
                'question'                => 'How does EduFlow handle search, filtering, pagination, and large amounts of school data?',
                'slug'                    => 'how-does-eduflow-handle-search-filtering-pagination-and-large-amounts-of-school-data',
                'answer'                  => 'The platform utilizes optimized database indexes, server-side pagination, and deterministic search queries across tables (such as students, staff, fees, and FAQs) to ensure fast data retrieval without artificial delays or external dependencies.',
                'category'                => 'System / Troubleshooting',
                'status'                  => 'published',
                'is_featured_on_homepage' => false,
                'sort_order'              => 16,
                'published_at'            => now(),
            ],
            [
                'question'                => 'How does EduFlow protect school data and prevent one school\'s users from accessing another school\'s data?',
                'slug'                    => 'how-does-eduflow-protect-school-data-and-prevent-cross-tenant-access',
                'answer'                  => 'EduFlow enforces strict multi-tenant isolation using automatic school scope global filters on database queries. This ensures that users from one school tenant cannot view, modify, or export records belonging to another school.',
                'category'                => 'Security',
                'status'                  => 'published',
                'is_featured_on_homepage' => true,
                'sort_order'              => 17,
                'published_at'            => now(),
            ],
            [
                'question'                => 'How does EduFlow manage user roles, permissions, and administrative access?',
                'slug'                    => 'how-does-eduflow-manage-user-roles-permissions-and-administrative-access',
                'answer'                  => 'Role-Based Access Control (RBAC) governs platform permissions. Users are assigned specific roles (such as super-admin, school-admin, teacher, accountant, librarian, or parent) which restrict access to authorized modules, routes, and administrative actions.',
                'category'                => 'Security',
                'status'                  => 'published',
                'is_featured_on_homepage' => false,
                'sort_order'              => 18,
                'published_at'            => now(),
            ],
            [
                'question'                => 'Can EduFlow support different schools, school configurations, modules, and subscription arrangements?',
                'slug'                    => 'can-eduflow-support-different-schools-school-configurations-modules-and-subscriptions',
                'answer'                  => 'Yes. EduFlow supports multi-school tenant onboarding, package subscription tiers, and modular feature toggles. Super administrators can configure platform settings, manage subscription billing, and enable or disable specific modules per school tenant.',
                'category'                => 'School Management',
                'status'                  => 'published',
                'is_featured_on_homepage' => false,
                'sort_order'              => 19,
                'published_at'            => now(),
            ],
            [
                'question'                => 'How does EduFlow improve day-to-day school administration and reduce manual work?',
                'slug'                    => 'how-does-eduflow-improve-day-to-day-school-administration-and-reduce-manual-work',
                'answer'                  => 'By centralizing admissions, grading, fee collection, HR, and inventory into a single interconnected system, EduFlow eliminates repetitive paperwork, reduces calculation errors, automates report generation, and gives administrators instant visibility into campus performance.',
                'category'                => 'General / Account',
                'status'                  => 'published',
                'is_featured_on_homepage' => true,
                'sort_order'              => 20,
                'published_at'            => now(),
            ],
        ];

        foreach ($faqs as $faq) {
            Faq::updateOrCreate(
                ['slug' => $faq['slug']],
                $faq
            );
        }
    }
}