services:
  - type: web
    name: eduflow-saas
    env: php
    region: frankfurt
    plan: free
    buildCommand: "composer install --no-dev --optimize-autoloader && npm install && npm run build && mkdir -p storage/framework/cache/data storage/framework/sessions storage/framework/views storage/logs bootstrap/cache && php artisan config:clear && php artisan cache:clear && mkdir -p storage/framework/cache/data && chmod -R 777 storage bootstrap/cache && touch database/database.sqlite && php artisan migrate --force && php artisan db:seed --force && php artisan storage:link"
    startCommand: "mkdir -p storage/framework/cache/data storage/framework/sessions storage/framework/views storage/logs bootstrap/cache storage/app/public storage/app/public/platform storage/app/public/branding storage/app/public/branding/register && chmod -R ugo+rwX storage bootstrap/cache && php artisan storage:link --force && php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: CACHE_STORE
        value: array
      - key: CACHE_DRIVER
        value: array